config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  get "up" => "rails/health#show", as: :rails_health_check
  
  devise_for :users
  scope '/admin' do
    resources :users
  end

  resources :roles

  get "rolunk", to: "static#about"
  
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users, dependent: :restrict_with_exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!  
  load_and_authorize_resource

  def index
    @roles = Role.all
  end

  def show
    if @role.users.empty?
      @assosciated_user = 'None'
    else
      @assosciated_users = @role.users.map(&:name).join(', ')
    end
  end

  def new
  end

  def edit
  end

  def create
    if @role.save
      redirect_to @role, notice: "Role was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: "Role was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @role.destroy!
    redirect_to roles_path, notice: "Role was successfully destroyed.", status: :see_other
  end

  private
    def role_params
      params.expect(role: [ :name, :description ])
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= role.description %>
  </p>

  <p>
    <strong>Assosciated users:</strong>
    <%= @assosciated_users %>
  </p>

</div>

app/views/roles/edit.html.erb
<% content_for :title, "Editing role" %>

<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Roles" %>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<% content_for :title, "New role" %>

<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>